/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsCustomerRouteImport } from './routes/terms-customer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsCustomerRoute = TermsCustomerRouteImport.update({
  id: '/terms-customer',
  path: '/terms-customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-customer': typeof TermsCustomerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-customer': typeof TermsCustomerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-customer': typeof TermsCustomerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/terms-and-conditions' | '/terms-customer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terms-and-conditions' | '/terms-customer'
  id: '__root__' | '/' | '/terms-and-conditions' | '/terms-customer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsCustomerRoute: typeof TermsCustomerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-customer': {
      id: '/terms-customer'
      path: '/terms-customer'
      fullPath: '/terms-customer'
      preLoaderRoute: typeof TermsCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsCustomerRoute: TermsCustomerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
